import { useEffect, useState } from "react";
import { ArrowLeft, Send, MessageSquare } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { listRequestMessages, sendRequestMessage, type CampusMessage, type CampusRequest } from "@/lib/campusos";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";

export default function CampusRequestConversation({request,onBack}:{request:CampusRequest;onBack:()=>void}){
 const {user}=useAuth();const {toast}=useToast();const [messages,setMessages]=useState<CampusMessage[]>([]);const [text,setText]=useState("");const [sending,setSending]=useState(false);
 useEffect(()=>{if(!user)return;let mounted=true;const load=async()=>{try{const data=await listRequestMessages(request.id);if(mounted)setMessages(data);}catch(e){toast({title:"Could not load conversation",description:e instanceof Error?e.message:"Try again.",variant:"destructive"});}};void load();const channel=supabase.channel(`request-chat-${request.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"campus_request_messages",filter:`request_id=eq.${request.id}`},payload=>{const item=payload.new as CampusMessage;setMessages(current=>current.some(x=>x.id===item.id)?current:[...current,item]);}).subscribe();return()=>{mounted=false;void supabase.removeChannel(channel);};},[request.id,user,toast]);
 const send=async()=>{if(!user||!text.trim()||sending)return;setSending(true);try{const item=await sendRequestMessage({requestId:request.id,userId:user.id,message:text,senderRole:"student"});setMessages(current=>current.some(x=>x.id===item.id)?current:[...current,item]);setText("");}catch(e){toast({title:"Message failed",description:e instanceof Error?e.message:"Try again.",variant:"destructive"});}finally{setSending(false);}};
 return <div className="border border-[#17252a]/10 bg-white">
  <div className="flex items-center gap-3 border-b border-[#17252a]/10 p-4"><button onClick={onBack}><ArrowLeft className="h-4 w-4"/></button><div><div className="font-mono text-[9px] uppercase tracking-wider text-[#2b7a78]">REQUEST CONVERSATION</div><h3 className="font-black uppercase">{request.title}</h3><div className="font-mono text-[9px] text-[#4e6265]">{request.request_code}</div></div></div>
  <div className="max-h-[38vh] min-h-[180px] space-y-3 overflow-auto p-4">{messages.length===0?<div className="flex h-40 flex-col items-center justify-center text-center text-xs text-[#4e6265]"><MessageSquare className="mb-2 h-6 w-6"/><div>No messages yet.</div><div>Ask the responsible team a question about this request.</div></div>:messages.map(m=><div key={m.id} className={`flex ${m.sender_role==="student"?"justify-end":"justify-start"}`}><div className={`max-w-[85%] border p-3 ${m.sender_role==="student"?"border-[#2b7a78]/20 bg-[#def2f1]":"border-[#17252a]/10 bg-[#f7fcfc]"}`}><div className="text-xs leading-5 text-[#17252a]">{m.message}</div><div className="mt-2 font-mono text-[9px] uppercase text-[#839092]">{m.sender_role==="student"?"You":"Campus team"} · {new Date(m.created_at).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</div></div></div>)}</div>
  <div className="border-t border-[#17252a]/10 p-3"><div className="flex gap-2"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Ask the campus team..." rows={2} className="min-w-0 flex-1 resize-none border border-[#17252a]/15 bg-[#f7fcfc] px-3 py-2 text-xs outline-none focus:border-[#2b7a78]"/><button disabled={!text.trim()||sending} onClick={()=>void send()} className="self-stretch bg-[#17252a] px-4 text-white disabled:opacity-40"><Send className="h-4 w-4"/></button></div><div className="mt-1 font-mono text-[8px] uppercase text-[#839092]">Enter to send · Shift+Enter for new line</div></div>
 </div>;
}