import { useEffect, useState } from "react";
import { Send, X, Paperclip, FileText } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { sendRequestMessage, type CampusMessage } from "@/lib/campusos";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";

export default function AdminRequestConversation({request,onClose}:{request:{id:string;title:string;request_code:string;user_id:string};onClose:()=>void}){
 const {user}=useAuth();const {toast}=useToast();const [messages,setMessages]=useState<CampusMessage[]>([]);const [text,setText]=useState("");const [file,setFile]=useState<File|null>(null);const [sending,setSending]=useState(false);
 useEffect(()=>{let mounted=true;const load=async()=>{const {data,error}=await supabase.from("campus_request_messages").select("id,request_id,user_id,sender_role,message,created_at,attachment_path,attachment_name").eq("request_id",request.id).order("created_at",{ascending:true});if(error)toast({title:"Could not load conversation",description:error.message,variant:"destructive"});if(mounted)setMessages((data as CampusMessage[])??[]);};void load();const channel=supabase.channel(`admin-request-chat-${request.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"campus_request_messages",filter:`request_id=eq.${request.id}`},payload=>{const item=payload.new as CampusMessage;setMessages(current=>current.some(x=>x.id===item.id)?current:[...current,item]);}).subscribe();return()=>{mounted=false;void supabase.removeChannel(channel);};},[request.id,toast]);
 const send=async()=>{if(!user||(!text.trim()&&!file)||sending)return;if(file&&file.size>10*1024*1024){toast({title:"File too large",description:"Attachments must be 10 MB or smaller."});return;}setSending(true);try{let attachmentPath:string|null=null;let attachmentName:string|null=null;if(file){attachmentPath=`${user.id}/${request.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const upload=await supabase.storage.from("campus-request-attachments").upload(attachmentPath,file,{upsert:false});if(upload.error)throw upload.error;attachmentName=file.name;}const item=await sendRequestMessage({requestId:request.id,userId:user.id,message:text||"Attachment sent.",senderRole:"admin",attachmentPath,attachmentName});setMessages(current=>current.some(x=>x.id===item.id)?current:[...current,item]);setText("");setFile(null);}catch(e){toast({title:"Reply failed",description:e instanceof Error?e.message:"Try again.",variant:"destructive"});}finally{setSending(false);}};
 return <div className="fixed inset-0 z-[10020] flex items-center justify-center bg-[#0b192c]/50 p-4"><section className="w-full max-w-lg border border-[#17252a]/15 bg-[#f7fcfc] shadow-2xl"><header className="flex items-start justify-between border-b border-[#17252a]/10 bg-[#17252a] p-5 text-white"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#9bd5d2]">CampusOS / Student communication</div><h2 className="mt-1 text-xl font-black uppercase">{request.title}</h2><div className="mt-1 font-mono text-[9px] text-white/60">{request.request_code} · {request.user_id.slice(0,8)}</div></div><button onClick={onClose}><X className="h-5 w-5"/></button></header><div className="max-h-[52vh] min-h-[220px] space-y-3 overflow-auto p-5">{messages.length===0?<div className="py-16 text-center text-sm text-[#4e6265]">No conversation yet. Send a clarification to the student.</div>:messages.map(m=><div key={m.id} className={`flex ${m.sender_role==="admin"?"justify-end":"justify-start"}`}><div className={`max-w-[85%] border p-3 ${m.sender_role==="admin"?"border-[#1f8f91]/20 bg-[#def2f1]":"border-[#17252a]/10 bg-white"}`}><div className="text-xs leading-5">{m.message}</div>{m.attachment_path&&<button onClick={async()=>{const {data,error}=await supabase.storage.from("campus-request-attachments").createSignedUrl(m.attachment_path!,300);if(error)toast({title:"Could not open attachment",description:error.message,variant:"destructive"});else if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer");}} className="mt-2 flex items-center gap-2 text-[10px] font-bold uppercase text-[#2b7a78]"><FileText className="h-3 w-3"/>{m.attachment_name||"Attachment"} →</button>}<div className="mt-2 font-mono text-[8px] uppercase text-[#839092]">{m.sender_role==="admin"?"You":"Student"} · {new Date(m.created_at).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</div></div></div>)}</div><div className="border-t border-[#17252a]/10 p-3"><div className="flex items-end gap-2"><label className="flex h-10 w-10 cursor-pointer items-center justify-center border border-[#17252a]/15 bg-white"><Paperclip className="h-4 w-4"/><input type="file" className="hidden" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Message the student..." rows={2} className="min-w-0 flex-1 resize-none border border-[#17252a]/15 bg-white px-3 py-2 text-xs outline-none focus:border-[#1f8f91]"/><button disabled={(!text.trim()&&!file)||sending} onClick={()=>void send()} className="self-stretch bg-[#1f8f91] px-4 text-white disabled:opacity-40"><Send className="h-4 w-4"/></button></div></div></section></div>;
}